---

- name: pip check
  shell: which pip && echo 'Found' || echo ''
  register: pip  
  
- name: get get-pip
  get_url: >
    url=https://bootstrap.pypa.io/get-pip.py
    dest={{ get_pip_src }}
  when: pip.stdout == ""

- name: install pip
  shell: cd {{ get_pip_src }} && python get-pip.py
  when: pip.stdout == ""  
  
- name: pip virtualenv check
  shell: pip freeze | grep virtualenv && echo 'Found' || echo ''
  register: pip
  
- name: pip install virtualenv
  command: pip install -U virtualenv
  when: pip.stdout == ""

- name: pip virtualenvwrapper check
  shell: pip freeze | grep virtualenvwrapper && echo 'Found' || echo ''
  register: pip  
    
- name: pip install virtualenvwrapper
  command: pip install virtualenvwrapper
  when: pip.stdout == ""

- name: which virtualenvwrapper.sh
  command: which virtualenvwrapper.sh
  register: which_virtualenvwrapper

- name: cp virtualenvwrapper.sh
  shell: cp {{ which_virtualenvwrapper.stdout }} /etc/profile.d/

  
- name: mkvirtualenv sentry
  shell: /bin/bash -lc 'mkvirtualenv {{ sentry_virtualenv }}'