---
- name: check pip installed
  shell: which pip
  register: result
  failed_when: result.rc not in [0, 1]
  
- name: get get-pip
  get_url: >
    url=https://bootstrap.pypa.io/get-pip.py
    dest={{ get_pip_src }}
  when: result.rc == 1

- name: install pip
  command: python get-pip.py chdir={{ get_pip_src }}
  when: result.rc == 1
  
- name: check virtualenv installed
  shell: pip freeze | grep -q virtualenv
  register: result
  failed_when: result.rc not in [0, 1]  
  
- name: install virtualenv
  command: pip install -U virtualenv
  when: result.rc == 1

- name: check virtualenvwrapper installed
  shell: pip freeze | grep -q virtualenvwrapper
  register: result
  failed_when: result.rc not in [0, 1]
  
- name: install virtualenvwrapper
  command: pip install virtualenvwrapper
  when: result.rc == 1  

- name: which virtualenvwrapper.sh
  command: which virtualenvwrapper.sh
  register: which_virtualenvwrapper

- name: link virtualenvwrapper.sh
  file: src={{ which_virtualenvwrapper.stdout }} dest=/etc/profile.d/virtualenvwrapper.sh state=link