---

- name: mkvirtualenv sentry
  command: su - {{ sentry_user }}  -l -c 'mkvirtualenv {{ sentry_virtualenv }}'
  remote_user: vagrant
  
- name: requirements modules
  apt: name={{ item }} state=installed
  with_items:
    - python-dev
    - libxml2-dev
    - libxslt-dev
    - zlib1g-dev
    - libffi-dev
    - libssl-dev
  when: ansible_os_family == "Debian"

#- name: workon sentry
#  command: su - {{ sentry_user }} -l -c 'workon {{ sentry_virtualenv }}'
  
- name: sentry check
  shell: su - {{ sentry_user }} -c "pip freeze | grep sentry && echo 'Found' || echo ''"
  register: pip

- name: pip install sentry
  command: su - {{ sentry_user }} -c 'sudo /home/{{ sentry_user }}/.virtualenvs/{{ sentry_virtualenv }}/bin/pip install -U sentry'
  when: pip.stdout == ""

